apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: jvlr9510/debeziumpostgres:dev
          ports:
            - containerPort: 5432
          env: 
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: database-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_HOST_AUTH_METHOD
              valueFrom:
                secretKeyRef:
                  name: database-secrets
                  key: POSTGRES_HOST_AUTH_METHOD
          volumeMounts:
            - name: secret-volume
              mountPath: /etc/secrets
            - name: init-scripts
              mountPath: /docker-entrypoint-initdb.d  
      volumes:
        - name: secret-volume
          secret:
            secretName: database-secrets
        - name: init-scripts
          configMap:
            name: postgres-init-scripts  
